### ISSUE TITLE
e?.address.replaceAll is not a function

### ISSUE THREAD

**Issue by mixman68** [mwood77/pf2opn#30]
Hello

Just tried the product, and I have this error

main.e88ec901367bee90.js:1 ERROR TypeError: e?.address.replaceAll is not a function
    at t.mapAliasEntity (main.e88ec901367bee90.js:1:244134)
    at main.e88ec901367bee90.js:1:242827
    at Array.forEach (<anonymous>)
    at t.mapPFtoOPN (main.e88ec901367bee90.js:1:242803)
    at o.onload (main.e88ec901367bee90.js:1:241830)
    at v.invoke (polyfills.18a047f7d412b1c1.js:1:6562)
    at Object.onInvoke (main.e88ec901367bee90.js:1:53367)
    at v.invoke (polyfills.18a047f7d412b1c1.js:1:6502)
    at L.runGuarded (polyfills.18a047f7d412b1c1.js:1:2066)
    at FileReader.<anonymous> (polyfills.18a047f7d412b1c1.js:1:1

**Comment by mwood77** [comment]
Hi, can you please show my what your System Aliases section looks like?

```
<system>
...
...
    <aliases>
        <alias>
        ....
        <alias>
    <aliases>
</system>
```

I don't need to see the content (bit between the tags), only the tags.

thanks!

**Comment by mixman68** [comment]
> Hi, can you please show my what your Aliases section looks like, and whether or not it's nested somewhere in another tag?
> 
> ```
> <aliases>
>     <alias>
>        ....
>     <alias>
> <aliases>
> ```
> 
> I don't need to see the content (bit between the tags), only the tags in each alias entry.
> 
> thanks!

![image](https://github.com/mwood77/pf2opn/assets/3840229/9fdd12b8-cb06-4254-8c6f-20b9a0640975)
this ?

**Comment by mwood77** [comment]
Yes, that's great. And that alias nested within a parent tag of `<aliases> ... </aliases>` right?

**Comment by mixman68** [comment]
Yes. But maybe i have non existant aliases relic in alias->address, i  don't know how check that easy, it is a big firewall
